name: Dry Release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup NodeJS 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: miranum-copilot
          path: |
            dist/
            images/
            resources/
            .vscodeignore
            LICENSE
            README.md
            CHANGELOG.md
            package.json

  package-miranum-copilot:
    runs-on: ubuntu-latest
    needs:
      - build
      - create-release
    steps:
      - name: Setup NodeJS 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/download-artifact@v4
        with:
          name: miranum-copilot
      - name: Prepare
        run: npm install -g @vscode/vsce@latest
      - name: Build vsce package
        run: vsce package --out miranum-copilot.vsix
      - uses: actions/upload-artifact@v4
        with:
          name: miranum-copilot
          path: ./miranum-copilot.vsix
